FROM ruby:3.0.2 AS main

RUN apt update -qq
RUN apt install -y \
    build-essential \
    libpq-dev \
    postgresql


RUN gem install bundler:2.4.0

WORKDIR /app

COPY Gemfile Gemfile.lock ./

RUN bundle install

ADD . .

